server {
    listen 80;
    server_name localhost;

    # Путь к собранным файлам React
    root /usr/share/nginx/html;
    index index.html;

    # Главный маршрут
    location / {
        # Если файл не найден, отдаем index.html (важно для SPA приложений)
        try_files $uri $uri/ /index.html;
    }

    # Настройка кэширования для статики (JS, CSS, картинки, JSON)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|mp4|json|woff2?)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }

    # Включаем Gzip сжатие для ускорения загрузки
    gzip on;
    gzip_min_length 1000;
    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;
}